### ISSUE TITLE
Inventory Items / Numberheld is not resetted

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#17]
This is easy seeable in the "Medium Red Potion".
It often turns to 36.

**Comment by itsschwer** [comment]
This is expected behaviour. Changes to Scriptable Objects persist between play mode and edit mode. This does not occur in builds.

We could make `InventoryItem` implement `ISerializationCallbackReceiver` to reset the `numberHeld` to 0 when exiting play mode. However, this would mean having to manually add items each time you want to test, or require a working save/load system to load an existing save to test.

**Comment by chameleonkid** [comment]
Issues seems to be solved.
