### ISSUE TITLE
Inventory Items get lost when saving / loading

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#18]
Reproduce steps:

-Get a lot of items and dont put them on
-Get two items of one kind. (2 Spellbooks)
-Equip 1 book
-Save
-Swap the books
-Load

-Several items might be missing 
-Inventory Size remains the same but a lot of null is added which will break the game
-Inventory must be manually reset after

**Comment by chameleonkid** [comment]
I think the problem is, that the SO itself is saved and not the _Numberheld.

**Comment by itsschwer** [comment]
This is an issue with the current saving system, confounded with the expected behaviour of Scriptable Objects (changes to Scriptable Objects persist between play mode and edit mode).

The current implementation only saves which items are in `Inventory.contents`, but no information about the items themselves (so `numberHeld` is not saved).

#### Example
- Let `EquipA` and `EquipB` be different equippables of the same type.
- When you equip `EquipA`, its `numberHeld` is reduced to `0`.
- Saving now will record `currentEquip` = `EquipA`.
- We then swap the books, so `EquipA.numberHeld` is now `1`, `EquipB.numberHeld` is now `0`, and `currentEquip` = `EquipB`.
- Loading the previous save, `currentEquip` will be set to `EquipA`, meaning that `EquipB` is not equipped *and* has a `numberHeld` of 0.
- The `InventoryManager` does not create slots for unequipped items with a `numberHeld <= 0`, so `EquipB` no longer is shown in the UI.

**Comment by itsschwer** [comment]
Pull request #20 attempts to implement a working save system. Please check if this issue persists on your end after merging.

**Comment by chameleonkid** [comment]
This issue seems to be solved. 
I'll give it a 3day-testing-phase and will close it after that.

**Comment by chameleonkid** [comment]
Thanks to schwer this issue seems fixed.
