### ISSUE TITLE
CurrentItems get Lost when loading in builds

### ISSUE THREAD

**Issue by chameleonkid** [chameleonkid/Secrets#66]
Repro:
1 Build the Game.
2 Save an more or less empty character.
3 Grab some items.
4 Save into another Slot.
5 Load the "Empty-Character" Slot.
6 Load the "Slot that has items equipped".
7 See that all Items that should be eqipped are gone!

**Comment by itsschwer** [comment]
Issue due to equipped items being saved by reference instead of by id. Unequipped items are not affected as they are correctly saved by id.

Trying to load items by reference in a build is not possible, as ES3 seems to not maintain `ScriptableObject` references between: build and editor; destructive scene changes; and play sessions. In other words, the generated `ES3Ref` for each `ScriptableObject` in the editor is not persistent (likely due to Unity limitations for how assets can be identified at runtime), meaning that loading will fail due to missing references.
